### ISSUE TITLE
Wear app not working

### ISSUE THREAD

**Issue by PsycheEYE** [devmil/parrot-zik-2-supercharge#1]
i tryed to patch new parrot zik app (version 1.4)
Your api works perfectly, but official wear app not working

**Comment by devmil** [comment]
Yes. The problem is that the wear app gets lost while decompiling the source apk.
I have to search for a way to preserve the wear app and re-sign it with the key the new Parrot Zik app gets signed with so that it gets transferred to the wearable.

**Comment by PsycheEYE** [comment]
Thx, I'll try it.

**Comment by PsycheEYE** [comment]
it works, maybe resigning wear apk must be added to scripts?
